@extends('layouts.app')
@section('title', 'Главная')

@section('content')
    <h3 class="text-2xl font-bold text-center text-blue-700 pb-3">Последние загрузки</h3>
    <ul class="flex flex-wrap justify-between">
        <li class="pb-5 transition transform ease-in-out duration-300 hover:-translate-y-1 hover:scale-105 motion-reduce:hover:transform-none"><a href=""><img src="/images/300x450.webp" alt="Постер" title="" width="200px"><h4 style="width: 200px;">Довод (2020, фантастика)</h4></a></li>
        <li class="pb-5 transition transform ease-in-out duration-300 hover:-translate-y-1 hover:scale-105 motion-reduce:hover:transform-none"><a href=""><img src="/images/300x450.webp" alt="Постер" title="" width="200px"><h4 style="width: 200px;">Довод (2020, фантастика)</h4></a></li>
        <li class="pb-5 transition transform ease-in-out duration-300 hover:-translate-y-1 hover:scale-105 motion-reduce:hover:transform-none"><a href=""><img src="/images/300x450.webp" alt="Постер" title="" width="200px"><h4 style="width: 200px;">Довод (2020, фантастика)</h4></a></li>
        <li class="pb-5 transition transform ease-in-out duration-300 hover:-translate-y-1 hover:scale-105 motion-reduce:hover:transform-none"><a href=""><img src="/images/300x450.webp" alt="Постер" title="" width="200px"><h4 style="width: 200px;">Довод (2020, фантастика)</h4></a></li>
        <li class="pb-5 transition transform ease-in-out duration-300 hover:-translate-y-1 hover:scale-105 motion-reduce:hover:transform-none"><a href=""><img src="/images/300x450.webp" alt="Постер" title="" width="200px"><h4 style="width: 200px;">Довод (2020, фантастика)</h4></a></li>
        <li class="pb-5 transition transform ease-in-out duration-300 hover:-translate-y-1 hover:scale-105 motion-reduce:hover:transform-none"><a href=""><img src="/images/300x450.webp" alt="Постер" title="" width="200px"><h4 style="width: 200px;">Довод (2020, фантастика)</h4></a></li>
        <li class="pb-5 transition transform ease-in-out duration-300 hover:-translate-y-1 hover:scale-105 motion-reduce:hover:transform-none"><a href=""><img src="/images/300x450.webp" alt="Постер" title="" width="200px"><h4 style="width: 200px;">Довод (2020, фантастика)</h4></a></li>
        <li class="pb-5 transition transform ease-in-out duration-300 hover:-translate-y-1 hover:scale-105 motion-reduce:hover:transform-none"><a href=""><img src="/images/300x450.webp" alt="Постер" title="" width="200px"><h4 style="width: 200px;">Довод (2020, фантастика)</h4></a></li>
        <li class="pb-5 transition transform ease-in-out duration-300 hover:-translate-y-1 hover:scale-105 motion-reduce:hover:transform-none"><a href=""><img src="/images/300x450.webp" alt="Постер" title="" width="200px"><h4 style="width: 200px;">Довод (2020, фантастика)</h4></a></li>
        <li class="pb-5 transition transform ease-in-out duration-300 hover:-translate-y-1 hover:scale-105 motion-reduce:hover:transform-none"><a href=""><img src="/images/300x450.webp" alt="Постер" title="" width="200px"><h4 style="width: 200px;">Довод (2020, фантастика)</h4></a></li>
        <li class="pb-5 transition transform ease-in-out duration-300 hover:-translate-y-1 hover:scale-105 motion-reduce:hover:transform-none"><a href=""><img src="/images/300x450.webp" alt="Постер" title="" width="200px"><h4 style="width: 200px;">Довод (2020, фантастика)</h4></a></li>
        <li class="pb-5 transition transform ease-in-out duration-300 hover:-translate-y-1 hover:scale-105 motion-reduce:hover:transform-none"><a href=""><img src="/images/300x450.webp" alt="Постер" title="" width="200px"><h4 style="width: 200px;">Довод (2020, фантастика)</h4></a></li>
        <li class="pb-5 transition transform ease-in-out duration-300 hover:-translate-y-1 hover:scale-105 motion-reduce:hover:transform-none"><a href=""><img src="/images/300x450.webp" alt="Постер" title="" width="200px"><h4 style="width: 200px;">Довод (2020, фантастика)</h4></a></li>
        <li class="pb-5 transition transform ease-in-out duration-300 hover:-translate-y-1 hover:scale-105 motion-reduce:hover:transform-none"><a href=""><img src="/images/300x450.webp" alt="Постер" title="" width="200px"><h4 style="width: 200px;">Довод (2020, фантастика)</h4></a></li>
        <li class="pb-5 transition transform ease-in-out duration-300 hover:-translate-y-1 hover:scale-105 motion-reduce:hover:transform-none"><a href=""><img src="/images/300x450.webp" alt="Постер" title="" width="200px"><h4 style="width: 200px;">Довод (2020, фантастика)</h4></a></li>
        <li class="pb-5 transition transform ease-in-out duration-300 hover:-translate-y-1 hover:scale-105 motion-reduce:hover:transform-none"><a href=""><img src="/images/300x450.webp" alt="Постер" title="" width="200px"><h4 style="width: 200px;">Довод (2020, фантастика)</h4></a></li>
    </ul>
@endsection
